apiVersion: v1
kind: Service
metadata:
  name: pocketbase
  namespace: aigc-develop
spec:
  selector:
    app: pocketbase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP 