apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chatbi

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - secret.yaml
  - env-secret.yaml
  - hpa.yaml

commonLabels:
  app: chatbi
  environment: production 